### ISSUE TITLE
🐞 Bug: runtime error: index out of range [15] with length 14

### ISSUE THREAD

**Issue by habaneraa** [sammcj/gollama#102]
## Description

Gollama crashes.

## How to reproduce

Not clear what data leads to this crash. On my machine there is a suspicious model: "shaw/dmeta-embedding-zh:latest". After deleted this model, Gollama works well.

## Screenshots / Logs

```
Caught panic:

runtime error: index out of range [15] with length 14

Restoring terminal...

goroutine 1 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.22.4/x64/src/runtime/debug/stack.go:24 +0x5e
runtime/debug.PrintStack()
        /opt/hostedtoolcache/go/1.22.4/x64/src/runtime/debug/stack.go:16 +0x13
github.com/charmbracelet/bubbletea.(*Program).Run.func1()
        /home/runner/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.26.6/tea.go:479 +0x91
panic({0x822ea0?, 0xc000276eb8?})
        /opt/hostedtoolcache/go/1.22.4/x64/src/runtime/panic.go:770 +0x132
main.quantColour({0xc000244460, 0x3})
        /home/runner/work/gollama/gollama/styles.go:71 +0xfc
main.itemDelegate.Render({_}, {_, _}, {0x1, 0x1, 0x1, 0x1, 0x1, 0x1, {0x8510c0, ...}, ...}, ...)
        /home/runner/work/gollama/gollama/item_delegate.go:69 +0x770
github.com/charmbracelet/bubbles/list.Model.populatedView({0x1, 0x1, 0x1, 0x1, 0x1, 0x1, {0x8510c0, 0x4}, {0x851475, 0x5}, ...})
        /home/runner/go/pkg/mod/github.com/charmbracelet/bubbles@v0.18.0/list/list.go:1185 +0x29f
github.com/charmbracelet/bubbles/list.Model.View({0x1, 0x1, 0x1, 0x1, 0x1, 0x1, {0x8510c0, 0x4}, {0x851475, 0x5}, ...})
        /home/runner/go/pkg/mod/github.com/charmbracelet/bubbles@v0.18.0/list/list.go:1036 +0x450
main.(*AppModel).View(0xc00028a008)
        /home/runner/work/gollama/gollama/app_model.go:607 +0xbe
github.com/charmbracelet/bubbletea.(*Program).Run(0xc0002c4100)
        /home/runner/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.26.6/tea.go:534 +0x87c
main.main()
        /home/runner/work/gollama/gollama/main.go:319 +0x1ed7

```

## Environment

- OS and version: Ubuntu 24.04
- Install source: Downloaded from releases

## Can you contribute?

- [ ] I will attempt to implement a fix for this bug

**Comment by habaneraa** [comment]
I updated my Gollama to v1.27.3 and this bug disappears. Sorry!

**Comment by sammcj** [comment]
Interesting! No worries at all :)
